### ISSUE TITLE
BarChart bar is moved outside of container and overlaps with yAxis labels.

### ISSUE THREAD

**Issue by sobolev-alexey** [ecomfe/echarts#5981]
### One-line summary [问题简述]
Scaled bar element is getting to wide and overlaps with yAxis labels.
See screenshots

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.6.1
+ Browser version [浏览器类型和版本]: Chrome 59.0.3071.86 (Official Build) (64-bit)
+ OS Version [操作系统类型和版本]: macOS Sierra 10.12.5

### Other comments [其他信息]

![barchart_width](https://user-images.githubusercontent.com/18738760/27045770-572bd734-4fa2-11e7-842b-467bae3b0021.gif)

![image](https://user-images.githubusercontent.com/18738760/27042139-66a8dd8a-4f96-11e7-823f-29ed493cd02b.png)

![image](https://user-images.githubusercontent.com/18738760/27042176-7e5539b0-4f96-11e7-93a9-740c57916ad5.png)

**Comment by pissang** [comment]
`xAxis.boundaryGap: true` ?

**Comment by sobolev-alexey** [comment]
@pissang yes, other xAxis configs:
```
    type: 'value',
    data: data,
    minInterval: 5,
    splitNumber: 4,
    min: 0,
    max: maxValue,
    gridIndex: index,
    axisLine: { onZero: false },
    axisTick: { show: false },
    axisLabel: {
      show: true,
      margin: 5,
    },
    splitLine: { show: false },
    showMinLabel: false,
    boundaryGap: true,
```

**Comment by pissang** [comment]
Can you put it on the jsfiddle? thanks.

**Comment by sobolev-alexey** [comment]
sure, I posted the code here: 
http://gallery.echartsjs.com/editor.html?c=xHkwrlhAz-&v=1
If you zoom and scroll to the right, you'll see the orange bar overlaps with yAxis.
Screenshot attached.
![barchart](https://user-images.githubusercontent.com/18738760/27133072-427301b2-5111-11e7-95a2-8757519a4c4e.gif)

**Comment by pissang** [comment]
Great. will check it out!

**Comment by pissang** [comment]
Found you are using `time` type in xAxis. `time` axis is continuous and much more like `value` type. You should use `category` type xAxis when using `bar` series. Or use `line` series instead if you insist on `time` xAxis.

**Comment by sobolev-alexey** [comment]
Thanks, @pissang, changing type to `category` fixed the issue.

**Comment by ahmadalibaloch** [comment]
Another option is to use `offset` for yAxis. Which will move yAxis to left side hence creating more space for bar. You may also need to limit bar width by `maxBarWidth` in bar series options.

**Comment by gshikhar94** [comment]
![Overlapping Issue Charts](https://user-images.githubusercontent.com/26906381/56655360-26a2ee00-66b0-11e9-9a04-1d27108f01a3.png)

Can you please help me, why bars are overlapping?

**Comment by eggachecat** [comment]
I don't think changing the type from 'time' to 'category' should be marked as a solution...

**Comment by arashkevich25** [comment]
any updates?

**Comment by mnischay** [comment]
@pissang @Ovilia : any updates on this ? can we using time as XAxis for bar charts in the near future ?

**Comment by hdonati-CFU** [comment]
any updates? Having the same issue now. I need the axis to be of type time because the data I'm displaying is coming from an API and is not always evenly spaced (e.g. it can be 1 hour apart for multiple datapoints then suddenly 3 days apart). 

Switching the xAxis to category, when the axis should be time, only works if the time difference between each datapoint is evenly spaced. 

Using offset and barMaxWidth works for some times, but not others (particularly when there's little data to display).

It'd be awesome if the outside of the chart could be on a different zLevel, for example, so that the bars would just be hidden underneath it when it overflows. I'm thinking of dealing with it by passing the data to the xAxis (e.g. ["2022-01-01T00:00:00.000Z", "2022-01-01T01:00:00.000Z", "2022-01-01T02:00:00.000Z", ...]) so that the "type:category" works, if there are no updates.

Here's what I'm working on for reference:
![image](https://github.com/user-attachments/assets/3afea54d-beb9-492a-a265-a103591a926e)

**Comment by Feroks** [comment]
any updates?

**Comment by alinscodes** [comment]
any updates?
