### ISSUE TITLE
How to add percentage to legend data?

### ISSUE THREAD

**Issue by jak65** [ecomfe/echarts#6344]
I am trying to add percentage to legend data of pie chart.
Using this pie chart demo:
https://ecomfe.github.io/echarts-examples/public/editor.html?c=pie-doughnut

Tried to add formatter ( formatter: "{a} <br/>{b}: {c} ({d}%)") to legend but does not work.

How to do this?

**Comment by pissang** [comment]
Legend formatter can't get percentage data. You need calculate it by yoursef

**Comment by j-robin-hunter** [comment]
I have just needed this. If you are simply trying to add the '%' symbol as a suffix to the legend name then formatter: "{name} %" worked for me

**Comment by HamzaSn** [comment]
> Legend formatter can't get percentage data. You need calculate it by yoursef

But if you calculate percentage yourself and pass it to the legend data in a pie chart for example, it will not show the legend , because it will try to find in the data "category (per%)" rather than just "category" , and it will not find it an output the following warning : 
category (0.38%) series not exists. Legend data should be same with series name or data name.
